parameters:
#    natura_pass_message.example.class: NaturaPass\MessageBundle\Example

services:
#    natura_pass_message.example:
#        class: %natura_pass_message.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
