parameters:
#    admin_graph.example.class: Admin\GraphBundle\Example

services:
#    admin_graph.example:
#        class: %admin_graph.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
