parameters:
#    admin_news.example.class: Admin\NewsBundle\Example

services:
#    admin_news.example:
#        class: %admin_news.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
